# Generated by Django 3.0.2 on 2020-02-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0002_auto_20200123_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total_level',
            name='totallevel',
            field=models.BooleanField(default=True),
        ),
    ]
