# Generated by Django 3.0.2 on 2020-02-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0003_auto_20200202_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='deploy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deploy', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='total_level',
            name='totallevel',
            field=models.IntegerField(default=100),
        ),
    ]
