# Generated by Django 3.0.2 on 2020-02-02 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0004_auto_20200202_2014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='deploy',
        ),
    ]
