# Generated by Django 2.1.4 on 2020-02-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0005_delete_deploy'),
    ]

    operations = [
        migrations.CreateModel(
            name='config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totallevel', models.IntegerField(default=30)),
                ('numlevel', models.IntegerField(default=30)),
            ],
        ),
        migrations.DeleteModel(
            name='total_level',
        ),
    ]
