# Generated by Django 3.0.2 on 2020-02-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0007_config_countdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='hint',
            field=models.TextField(default='na'),
        ),
    ]
