# Generated by Django 3.0.2 on 2020-03-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0008_level_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='time',
            field=models.CharField(default=1, max_length=40),
        ),
    ]
