# Generated by Django 3.0.2 on 2020-05-04 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0010_remove_config_show_lboard'),
        ('treasure', '0009_config_time'),
    ]

    operations = [
    ]
