# Generated by Django 3.0.2 on 2020-05-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0011_merge_20200504_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='display_audio',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='level',
            name='display_video',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='level',
            name='video',
            field=models.FileField(default='video/default.mp4', upload_to='video'),
        ),
        migrations.AlterField(
            model_name='level',
            name='audio',
            field=models.FileField(default='audio/audios/default.mp3', upload_to='audio'),
        ),
        migrations.AlterField(
            model_name='level',
            name='image',
            field=models.ImageField(default='images/images/level1.jpg', upload_to='images'),
        ),
    ]
