# Generated by Django 3.0.2 on 2020-05-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0012_auto_20200504_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='video',
            field=models.FileField(default='video/default.mkv', null=True, upload_to='video'),
        ),
    ]
