# Generated by Django 3.0.2 on 2020-05-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0014_auto_20200504_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='video',
            field=models.FileField(default='video/default.mp4', upload_to='video'),
        ),
    ]
