# Generated by Django 3.0.2 on 2020-05-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0015_auto_20200504_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='video',
            field=models.FileField(default='video/def.mp4', upload_to='video'),
        ),
    ]
