# Generated by Django 3.0.2 on 2020-06-22 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0017_auto_20200505_1332'),
        ('treasure', '0012_auto_20200516_1435'),
    ]

    operations = [
    ]
